module.exports = {
	help: `Shows the info of a Pokemon.`,
	permissions: 'none',
	commandFunction: function (Bot, room, time, by, args, client, isPM) {
		const CP_M = {
			"40": 0.7903,
			"50": 0.84029999,
			"51": 0.84529999
		};
		const shinies = {
			"abomasnow": true,
			"absol": true,
			"aerodactyl": true,
			"aipom": true,
			"alomomola": true,
			"altaria": true,
			"anorith": true,
			"arcanine": true,
			"aron": true,
			"azelf": true,
			"bagon": true,
			"barboach": true,
			"beedrill": true,
			"beldum": true,
			"bellsprout": true,
			"bidoof": true,
			"blastoise": true,
			"bonsly": true,
			"bronzor": true,
			"buizel": true,
			"bulbasaur": true,
			"bunnelby": true,
			"burmy": true,
			"carvanha": true,
			"castform": true,
			"castformrainy": true,
			"caterpie": true,
			"charizard": true,
			"charmander": true,
			"charmander": true,
			"chikorita": true,
			"chimchar": true,
			"chimchar": true,
			"chimecho": true,
			"chinchou": true,
			"clefairy": true,
			"cranidos": true,
			"cubchoo": true,
			"cyndaquil": true,
			"deino": true,
			"diglett": true,
			"diglettalola": true,
			"doduo": true,
			"dratini": true,
			"dunsparce": true,
			"durant": true,
			"duskull": true,
			"dwebble": true,
			"eevee": true,
			"electrike": true,
			"farfetchd": true,
			"farfetchdgalar": true,
			"feebas": true,
			"ferroseed": true,
			"fletchling": true,
			"fletchling": true,
			"gastly": true,
			"gastly": true,
			"gengar": true,
			"geodude": true,
			"geodudealola": true,
			"gible": true,
			"gible": true,
			"glameow": true,
			"gligar": true,
			"goldeen": true,
			"growlithe": true,
			"gyarados": true,
			"heatmor": true,
			"heracross": true,
			"hippopotas": true,
			"hitmonchan": true,
			"hitmonlee": true,
			"houndoom": true,
			"illumise": true,
			"jynx": true,
			"kabuto": true,
			"kangaskhan": true,
			"klink": true,
			"lapras": true,
			"larvitar": true,
			"ledyba": true,
			"lickitung": true,
			"lileep": true,
			"lillipup": true,
			"lotad": true,
			"lugia": true,
			"lunatone": true,
			"luvdisc": true,
			"machop": true,
			"machop": true,
			"magikarp": true,
			"magikarp": true,
			"magnemite": true,
			"makuhita": true,
			"manectric": true,
			"marill": true,
			"meditite": true,
			"meowth": true,
			"meowthgalar": true,
			"mesprit": true,
			"mimejr": true,
			"misdreavus": true,
			"mrmime": true,
			"mudkip": true,
			"murkrow": true,
			"natu": true,
			"nincada": true,
			"nosepass": true,
			"oddish": true,
			"omanyte": true,
			"onix": true,
			"pidgeot": true,
			"pidgey": true,
			"pidove": true,
			"pikachu": true,
			"pinsir": true,
			"piplup": true,
			"piplup": true,
			"poliwag": true,
			"ponyta": true,
			"ponytagalar": true,
			"poochyena": true,
			"porygon": true,
			"porygon": true,
			"psyduck": true,
			"qwilfish": true,
			"ralts": true,
			"rattataalola": true,
			"rhyhorn": true,
			"rhyhorn": true,
			"riolu": true,
			"roggenrola": true,
			"roselia": true,
			"roselia": true,
			"rufflet": true,
			"sableye": true,
			"sandshrewalola": true,
			"sawk": true,
			"scyther": true,
			"seedot": true,
			"seedot": true,
			"seedot": true,
			"seel": true,
			"sentret": true,
			"seviper": true,
			"shellder": true,
			"shieldon": true,
			"skarmory": true,
			"skitty": true,
			"skorupi": true,
			"slowbro": true,
			"slowpoke": true,
			"sneasel": true,
			"sneasel": true,
			"snorlax": true,
			"snorunt": true,
			"snover": true,
			"snubbull": true,
			"solrock": true,
			"spinda": true,
			"spoink": true,
			"squirtle": true,
			"stantler": true,
			"staryu": true,
			"stunfiskgalar": true,
			"sudowoodo": true,
			"sunkern": true,
			"swablu": true,
			"swablu": true,
			"swinub": true,
			"taillow": true,
			"tangela": true,
			"tauros": true,
			"tentacool": true,
			"throh": true,
			"timburr": true,
			"togepi": true,
			"torchic": true,
			"totodile": true,
			"trapinch": true,
			"treecko": true,
			"trubbish": true,
			"turtwig": true,
			"tympole": true,
			"unown": true,
			"uxie": true,
			"venonat": true,
			"venonat": true,
			"venusaur": true,
			"volbeat": true,
			"voltorb": true,
			"vulpix": true,
			"vulpixalola": true,
			"wailmer": true,
			"weedle": true,
			"weedle": true,
			"weezinggalar": true,
			"whismur": true,
			"wingull": true,
			"wobbuffet": true,
			"woobat": true,
			"wooper": true,
			"wurmple": true,
			"wynaut": true,
			"yanma": true,
			"zangoose": true,
			"zigzagoongalar": true,
			"zubat": true
		};
		let monID = toID(args.join(''));
		if (monID === 'constructor') return Bot.roomReply(room, by, 'Haha very funny');
		const mon = data.pokedex[monID];
		if (!mon) return Bot.roomReply(room, by, 'Uhh sorry I don\'t have that Pokemon in my Dex; try the base forme (or format the name the way it\'s seen on PS)?');
		const ms = mon.baseStats;
		const atks = [ms.atk, ms.spa].sort((a, b) => b - a);
		const defs = [ms.def, ms.spd].sort((a, b) => b - a);
		const nerfMod = 0.91;
		const stats = {
			atk: 0,
			def: 0,
			sta: Math.floor(ms.hp * 1.75 + 50)
		};
		const speedMod = 1 + (ms.spe - 75) / 500;
		let nerfed = false;
		stats.atk = Math.round(Math.round(7 * atks[0] / 4 + 1 * atks[1] / 4) * speedMod);
		stats.def = Math.round(Math.round(5 * defs[0] / 4 + 3 * defs[1] / 4) * speedMod);
		let L40_CP = Math.floor((stats.atk + 15) * (stats.def + 15) ** 0.5 * (stats.sta + 15) ** 0.5 * CP_M[40] ** 2 / 10);
		if (L40_CP > 4000 && !(mon.forme?.startsWith('Mega') && mon.baseSpecies !== 'Mewtwo' && mon.baseSpecies !== 'Rayquaza') && mon.forme !== 'Primal') {
			stats.atk = Math.round(Math.round(7 * atks[0] / 4 + 1 * atks[1] / 4) * speedMod * nerfMod);
			stats.def = Math.round(Math.round(5 * defs[0] / 4 + 3 * defs[1] / 4) * speedMod * nerfMod);
			stats.sta = Math.round((ms.hp * 1.75 + 50) * nerfMod);
			L40_CP = Math.floor((stats.atk + 15) * (stats.def + 15) ** 0.5 * (stats.sta + 15) ** 0.5 * CP_M[40] ** 2 / 10);
			nerfed = true;
		}
		const L50_CP = Math.floor((stats.atk + 15) * (stats.def + 15) ** 0.5 * (stats.sta + 15) ** 0.5 * CP_M[50] ** 2 / 10);
		const L51_CP = Math.floor((stats.atk + 15) * (stats.def + 15) ** 0.5 * (stats.sta + 15) ** 0.5 * CP_M[51] ** 2 / 10);
		const html = `<div class="message"><ul class="utilichart"><li class="result"><span class="col numcol">GO</span> <span class="col iconcol"><psicon pokemon="${monID}"/></span> <span class="col pokemonnamecol" style="white-space:nowrap"><a href="https://dex.pokemonshowdown.com/pokemon/${monID}" target="_blank">${mon.name}</a></span> <span class="col typecol">${mon.types.map(type => `<img src="https://play.pokemonshowdown.com/sprites/types/${type}.png" alt="${type}" height="14" width="32">`).join('')}</span> <span style="float:left;min-height:26px"><span class="col statcol"><em>Atk</em><br />${stats.atk}</span> <span class="col statcol"><em>Def</em><br />${stats.def}</span> <span class="col statcol"><em>Sta</em><br />${stats.sta}</span> <span class="col bstcol" style="margin-left:10px;"><em>40</em><br />${L40_CP}</span> <span class="col bstcol" style="margin-left:10px;"><em>50</em><br />${L50_CP}</span> <span class="col bstcol" style="margin-left:10px;"><em>MCP</em><br />${L51_CP}</span> </span></li><li style="clear:both"></li></ul></div><font size="1"><font color="#686868">Dex#:</font> ${mon.num}&nbsp;|&ThickSpace;<font color="#686868">Gen:</font> ${[0, 152, 252, 387, 495, 650, 722, 810, 1000].findIndex(num => mon.num < num)}&nbsp;|&ThickSpace;<font color="#686868">Height:</font> ${mon.heightm} m&nbsp;|&ThickSpace;<font color="#686868">Weight:</font> ${mon.weightkg} kg${shinies[monID] ? '&nbsp;|&ThickSpace; ✓ Can be shiny' : ''}&nbsp;|&ThickSpace;<font color="#686868">Evolution:</font> ${mon.evos?.join(', ') || 'None'}${nerfed ? '&nbsp;|&ThickSpace; ✓ 9% nerfed' : ''}</font>`;
		if (isPM) Bot.sendHTML(by, html);
		else if (tools.hasPermission(by, 'gamma', room)) Bot.say(room, `/addhtmlbox ${html}`);
		else Bot.say(room, `/sendprivatehtmlbox ${by}, ${html}`);
	}
}
